name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglib2.0-dev libcairo2-dev libatk1.0-dev libgtk-3-dev libxdo-dev libayatana-appindicator3-dev
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      working-directory: mousetool
      run: cargo build --verbose
    
    - name: Run tests
      working-directory: mousetool
      run: cargo test --verbose
